// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: advert.proto

package proto;

public final class AdvertProto {
  private AdvertProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AdvertReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AdvertReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 advertId = 1;</code>
     */
    boolean hasAdvertId();
    /**
     * <code>required int32 advertId = 1;</code>
     */
    int getAdvertId();
  }
  /**
   * <pre>
   * 广告请求
   *cmd:1015
   * </pre>
   *
   * Protobuf type {@code AdvertReq}
   */
  public  static final class AdvertReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AdvertReq)
      AdvertReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AdvertReq.newBuilder() to construct.
    private AdvertReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AdvertReq() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AdvertReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              advertId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.AdvertProto.internal_static_AdvertReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.AdvertProto.internal_static_AdvertReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.AdvertProto.AdvertReq.class, proto.AdvertProto.AdvertReq.Builder.class);
    }

    private int bitField0_;
    public static final int ADVERTID_FIELD_NUMBER = 1;
    private int advertId_;
    /**
     * <code>required int32 advertId = 1;</code>
     */
    public boolean hasAdvertId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 advertId = 1;</code>
     */
    public int getAdvertId() {
      return advertId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAdvertId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, advertId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, advertId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.AdvertProto.AdvertReq)) {
        return super.equals(obj);
      }
      proto.AdvertProto.AdvertReq other = (proto.AdvertProto.AdvertReq) obj;

      if (hasAdvertId() != other.hasAdvertId()) return false;
      if (hasAdvertId()) {
        if (getAdvertId()
            != other.getAdvertId()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAdvertId()) {
        hash = (37 * hash) + ADVERTID_FIELD_NUMBER;
        hash = (53 * hash) + getAdvertId();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.AdvertProto.AdvertReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.AdvertProto.AdvertReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.AdvertProto.AdvertReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.AdvertProto.AdvertReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.AdvertProto.AdvertReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.AdvertProto.AdvertReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.AdvertProto.AdvertReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.AdvertProto.AdvertReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.AdvertProto.AdvertReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.AdvertProto.AdvertReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.AdvertProto.AdvertReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.AdvertProto.AdvertReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.AdvertProto.AdvertReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 广告请求
     *cmd:1015
     * </pre>
     *
     * Protobuf type {@code AdvertReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AdvertReq)
        proto.AdvertProto.AdvertReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.AdvertProto.internal_static_AdvertReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.AdvertProto.internal_static_AdvertReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.AdvertProto.AdvertReq.class, proto.AdvertProto.AdvertReq.Builder.class);
      }

      // Construct using proto.AdvertProto.AdvertReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        advertId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.AdvertProto.internal_static_AdvertReq_descriptor;
      }

      @java.lang.Override
      public proto.AdvertProto.AdvertReq getDefaultInstanceForType() {
        return proto.AdvertProto.AdvertReq.getDefaultInstance();
      }

      @java.lang.Override
      public proto.AdvertProto.AdvertReq build() {
        proto.AdvertProto.AdvertReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.AdvertProto.AdvertReq buildPartial() {
        proto.AdvertProto.AdvertReq result = new proto.AdvertProto.AdvertReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.advertId_ = advertId_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.AdvertProto.AdvertReq) {
          return mergeFrom((proto.AdvertProto.AdvertReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.AdvertProto.AdvertReq other) {
        if (other == proto.AdvertProto.AdvertReq.getDefaultInstance()) return this;
        if (other.hasAdvertId()) {
          setAdvertId(other.getAdvertId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasAdvertId()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.AdvertProto.AdvertReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.AdvertProto.AdvertReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int advertId_ ;
      /**
       * <code>required int32 advertId = 1;</code>
       */
      public boolean hasAdvertId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int32 advertId = 1;</code>
       */
      public int getAdvertId() {
        return advertId_;
      }
      /**
       * <code>required int32 advertId = 1;</code>
       */
      public Builder setAdvertId(int value) {
        bitField0_ |= 0x00000001;
        advertId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 advertId = 1;</code>
       */
      public Builder clearAdvertId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        advertId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AdvertReq)
    }

    // @@protoc_insertion_point(class_scope:AdvertReq)
    private static final proto.AdvertProto.AdvertReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.AdvertProto.AdvertReq();
    }

    public static proto.AdvertProto.AdvertReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<AdvertReq>
        PARSER = new com.google.protobuf.AbstractParser<AdvertReq>() {
      @java.lang.Override
      public AdvertReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AdvertReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AdvertReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AdvertReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.AdvertProto.AdvertReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AdvertRspOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AdvertRsp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *是否成功;
     * </pre>
     *
     * <code>required bool isSucc = 1;</code>
     */
    boolean hasIsSucc();
    /**
     * <pre>
     *是否成功;
     * </pre>
     *
     * <code>required bool isSucc = 1;</code>
     */
    boolean getIsSucc();

    /**
     * <pre>
     *错误信息;
     * </pre>
     *
     * <code>optional string errMess = 2;</code>
     */
    boolean hasErrMess();
    /**
     * <pre>
     *错误信息;
     * </pre>
     *
     * <code>optional string errMess = 2;</code>
     */
    java.lang.String getErrMess();
    /**
     * <pre>
     *错误信息;
     * </pre>
     *
     * <code>optional string errMess = 2;</code>
     */
    com.google.protobuf.ByteString
        getErrMessBytes();
  }
  /**
   * <pre>
   * 广告返回
   *cmd:5015
   * </pre>
   *
   * Protobuf type {@code AdvertRsp}
   */
  public  static final class AdvertRsp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AdvertRsp)
      AdvertRspOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AdvertRsp.newBuilder() to construct.
    private AdvertRsp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AdvertRsp() {
      errMess_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AdvertRsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              isSucc_ = input.readBool();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              errMess_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.AdvertProto.internal_static_AdvertRsp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.AdvertProto.internal_static_AdvertRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.AdvertProto.AdvertRsp.class, proto.AdvertProto.AdvertRsp.Builder.class);
    }

    private int bitField0_;
    public static final int ISSUCC_FIELD_NUMBER = 1;
    private boolean isSucc_;
    /**
     * <pre>
     *是否成功;
     * </pre>
     *
     * <code>required bool isSucc = 1;</code>
     */
    public boolean hasIsSucc() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *是否成功;
     * </pre>
     *
     * <code>required bool isSucc = 1;</code>
     */
    public boolean getIsSucc() {
      return isSucc_;
    }

    public static final int ERRMESS_FIELD_NUMBER = 2;
    private volatile java.lang.Object errMess_;
    /**
     * <pre>
     *错误信息;
     * </pre>
     *
     * <code>optional string errMess = 2;</code>
     */
    public boolean hasErrMess() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     *错误信息;
     * </pre>
     *
     * <code>optional string errMess = 2;</code>
     */
    public java.lang.String getErrMess() {
      java.lang.Object ref = errMess_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errMess_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *错误信息;
     * </pre>
     *
     * <code>optional string errMess = 2;</code>
     */
    public com.google.protobuf.ByteString
        getErrMessBytes() {
      java.lang.Object ref = errMess_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errMess_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasIsSucc()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBool(1, isSucc_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errMess_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isSucc_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, errMess_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.AdvertProto.AdvertRsp)) {
        return super.equals(obj);
      }
      proto.AdvertProto.AdvertRsp other = (proto.AdvertProto.AdvertRsp) obj;

      if (hasIsSucc() != other.hasIsSucc()) return false;
      if (hasIsSucc()) {
        if (getIsSucc()
            != other.getIsSucc()) return false;
      }
      if (hasErrMess() != other.hasErrMess()) return false;
      if (hasErrMess()) {
        if (!getErrMess()
            .equals(other.getErrMess())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasIsSucc()) {
        hash = (37 * hash) + ISSUCC_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIsSucc());
      }
      if (hasErrMess()) {
        hash = (37 * hash) + ERRMESS_FIELD_NUMBER;
        hash = (53 * hash) + getErrMess().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.AdvertProto.AdvertRsp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.AdvertProto.AdvertRsp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.AdvertProto.AdvertRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.AdvertProto.AdvertRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.AdvertProto.AdvertRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.AdvertProto.AdvertRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.AdvertProto.AdvertRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.AdvertProto.AdvertRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.AdvertProto.AdvertRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.AdvertProto.AdvertRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.AdvertProto.AdvertRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.AdvertProto.AdvertRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.AdvertProto.AdvertRsp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 广告返回
     *cmd:5015
     * </pre>
     *
     * Protobuf type {@code AdvertRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AdvertRsp)
        proto.AdvertProto.AdvertRspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.AdvertProto.internal_static_AdvertRsp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.AdvertProto.internal_static_AdvertRsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.AdvertProto.AdvertRsp.class, proto.AdvertProto.AdvertRsp.Builder.class);
      }

      // Construct using proto.AdvertProto.AdvertRsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        isSucc_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        errMess_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.AdvertProto.internal_static_AdvertRsp_descriptor;
      }

      @java.lang.Override
      public proto.AdvertProto.AdvertRsp getDefaultInstanceForType() {
        return proto.AdvertProto.AdvertRsp.getDefaultInstance();
      }

      @java.lang.Override
      public proto.AdvertProto.AdvertRsp build() {
        proto.AdvertProto.AdvertRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.AdvertProto.AdvertRsp buildPartial() {
        proto.AdvertProto.AdvertRsp result = new proto.AdvertProto.AdvertRsp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.isSucc_ = isSucc_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.errMess_ = errMess_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.AdvertProto.AdvertRsp) {
          return mergeFrom((proto.AdvertProto.AdvertRsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.AdvertProto.AdvertRsp other) {
        if (other == proto.AdvertProto.AdvertRsp.getDefaultInstance()) return this;
        if (other.hasIsSucc()) {
          setIsSucc(other.getIsSucc());
        }
        if (other.hasErrMess()) {
          bitField0_ |= 0x00000002;
          errMess_ = other.errMess_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasIsSucc()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.AdvertProto.AdvertRsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.AdvertProto.AdvertRsp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean isSucc_ ;
      /**
       * <pre>
       *是否成功;
       * </pre>
       *
       * <code>required bool isSucc = 1;</code>
       */
      public boolean hasIsSucc() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *是否成功;
       * </pre>
       *
       * <code>required bool isSucc = 1;</code>
       */
      public boolean getIsSucc() {
        return isSucc_;
      }
      /**
       * <pre>
       *是否成功;
       * </pre>
       *
       * <code>required bool isSucc = 1;</code>
       */
      public Builder setIsSucc(boolean value) {
        bitField0_ |= 0x00000001;
        isSucc_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否成功;
       * </pre>
       *
       * <code>required bool isSucc = 1;</code>
       */
      public Builder clearIsSucc() {
        bitField0_ = (bitField0_ & ~0x00000001);
        isSucc_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object errMess_ = "";
      /**
       * <pre>
       *错误信息;
       * </pre>
       *
       * <code>optional string errMess = 2;</code>
       */
      public boolean hasErrMess() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       *错误信息;
       * </pre>
       *
       * <code>optional string errMess = 2;</code>
       */
      public java.lang.String getErrMess() {
        java.lang.Object ref = errMess_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            errMess_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *错误信息;
       * </pre>
       *
       * <code>optional string errMess = 2;</code>
       */
      public com.google.protobuf.ByteString
          getErrMessBytes() {
        java.lang.Object ref = errMess_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errMess_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *错误信息;
       * </pre>
       *
       * <code>optional string errMess = 2;</code>
       */
      public Builder setErrMess(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errMess_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *错误信息;
       * </pre>
       *
       * <code>optional string errMess = 2;</code>
       */
      public Builder clearErrMess() {
        bitField0_ = (bitField0_ & ~0x00000002);
        errMess_ = getDefaultInstance().getErrMess();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *错误信息;
       * </pre>
       *
       * <code>optional string errMess = 2;</code>
       */
      public Builder setErrMessBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errMess_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AdvertRsp)
    }

    // @@protoc_insertion_point(class_scope:AdvertRsp)
    private static final proto.AdvertProto.AdvertRsp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.AdvertProto.AdvertRsp();
    }

    public static proto.AdvertProto.AdvertRsp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<AdvertRsp>
        PARSER = new com.google.protobuf.AbstractParser<AdvertRsp>() {
      @java.lang.Override
      public AdvertRsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AdvertRsp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AdvertRsp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AdvertRsp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.AdvertProto.AdvertRsp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AdvertReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AdvertReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AdvertRsp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AdvertRsp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014advert.proto\032\nbase.proto\"\035\n\tAdvertReq\022" +
      "\020\n\010advertId\030\001 \002(\005\",\n\tAdvertRsp\022\016\n\006isSucc" +
      "\030\001 \002(\010\022\017\n\007errMess\030\002 \001(\tB\026\n\005protoB\013Advert" +
      "ProtoP\000"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          proto.BaseProto.getDescriptor(),
        }, assigner);
    internal_static_AdvertReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AdvertReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AdvertReq_descriptor,
        new java.lang.String[] { "AdvertId", });
    internal_static_AdvertRsp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AdvertRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AdvertRsp_descriptor,
        new java.lang.String[] { "IsSucc", "ErrMess", });
    proto.BaseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
