// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: battle.proto

package proto;

public final class BattleProto {
  private BattleProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BattleSettleReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BattleSettleReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *1：竞标赛 2：经典模式
     * </pre>
     *
     * <code>required int32 type = 1;</code>
     * @return Whether the type field is set.
     */
    boolean hasType();
    /**
     * <pre>
     *1：竞标赛 2：经典模式
     * </pre>
     *
     * <code>required int32 type = 1;</code>
     * @return The type.
     */
    int getType();

    /**
     * <pre>
     *本局积分
     * </pre>
     *
     * <code>required int32 score = 2;</code>
     * @return Whether the score field is set.
     */
    boolean hasScore();
    /**
     * <pre>
     *本局积分
     * </pre>
     *
     * <code>required int32 score = 2;</code>
     * @return The score.
     */
    int getScore();

    /**
     * <pre>
     *本局关卡
     * </pre>
     *
     * <code>required int32 checkPoint = 3;</code>
     * @return Whether the checkPoint field is set.
     */
    boolean hasCheckPoint();
    /**
     * <pre>
     *本局关卡
     * </pre>
     *
     * <code>required int32 checkPoint = 3;</code>
     * @return The checkPoint.
     */
    int getCheckPoint();

    /**
     * <pre>
     *倍数
     * </pre>
     *
     * <code>required int32 multiple = 4;</code>
     * @return Whether the multiple field is set.
     */
    boolean hasMultiple();
    /**
     * <pre>
     *倍数
     * </pre>
     *
     * <code>required int32 multiple = 4;</code>
     * @return The multiple.
     */
    int getMultiple();

    /**
     * <pre>
     *跳跃
     * </pre>
     *
     * <code>required int32 jump = 5;</code>
     * @return Whether the jump field is set.
     */
    boolean hasJump();
    /**
     * <pre>
     *跳跃
     * </pre>
     *
     * <code>required int32 jump = 5;</code>
     * @return The jump.
     */
    int getJump();

    /**
     * <pre>
     *跳跃段数
     * </pre>
     *
     * <code>required int32 jumpLevel = 6;</code>
     * @return Whether the jumpLevel field is set.
     */
    boolean hasJumpLevel();
    /**
     * <pre>
     *跳跃段数
     * </pre>
     *
     * <code>required int32 jumpLevel = 6;</code>
     * @return The jumpLevel.
     */
    int getJumpLevel();

    /**
     * <pre>
     *广告id
     * </pre>
     *
     * <code>required int32 advertId = 7;</code>
     * @return Whether the advertId field is set.
     */
    boolean hasAdvertId();
    /**
     * <pre>
     *广告id
     * </pre>
     *
     * <code>required int32 advertId = 7;</code>
     * @return The advertId.
     */
    int getAdvertId();
  }
  /**
   * <pre>
   *战斗结算
   *cmd:1010
   * </pre>
   *
   * Protobuf type {@code BattleSettleReq}
   */
  public  static final class BattleSettleReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BattleSettleReq)
      BattleSettleReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BattleSettleReq.newBuilder() to construct.
    private BattleSettleReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BattleSettleReq() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BattleSettleReq();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BattleSettleReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              type_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              score_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              checkPoint_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              multiple_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              jump_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              jumpLevel_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              advertId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.BattleProto.internal_static_BattleSettleReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.BattleProto.internal_static_BattleSettleReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.BattleProto.BattleSettleReq.class, proto.BattleProto.BattleSettleReq.Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <pre>
     *1：竞标赛 2：经典模式
     * </pre>
     *
     * <code>required int32 type = 1;</code>
     * @return Whether the type field is set.
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *1：竞标赛 2：经典模式
     * </pre>
     *
     * <code>required int32 type = 1;</code>
     * @return The type.
     */
    public int getType() {
      return type_;
    }

    public static final int SCORE_FIELD_NUMBER = 2;
    private int score_;
    /**
     * <pre>
     *本局积分
     * </pre>
     *
     * <code>required int32 score = 2;</code>
     * @return Whether the score field is set.
     */
    public boolean hasScore() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     *本局积分
     * </pre>
     *
     * <code>required int32 score = 2;</code>
     * @return The score.
     */
    public int getScore() {
      return score_;
    }

    public static final int CHECKPOINT_FIELD_NUMBER = 3;
    private int checkPoint_;
    /**
     * <pre>
     *本局关卡
     * </pre>
     *
     * <code>required int32 checkPoint = 3;</code>
     * @return Whether the checkPoint field is set.
     */
    public boolean hasCheckPoint() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     *本局关卡
     * </pre>
     *
     * <code>required int32 checkPoint = 3;</code>
     * @return The checkPoint.
     */
    public int getCheckPoint() {
      return checkPoint_;
    }

    public static final int MULTIPLE_FIELD_NUMBER = 4;
    private int multiple_;
    /**
     * <pre>
     *倍数
     * </pre>
     *
     * <code>required int32 multiple = 4;</code>
     * @return Whether the multiple field is set.
     */
    public boolean hasMultiple() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     *倍数
     * </pre>
     *
     * <code>required int32 multiple = 4;</code>
     * @return The multiple.
     */
    public int getMultiple() {
      return multiple_;
    }

    public static final int JUMP_FIELD_NUMBER = 5;
    private int jump_;
    /**
     * <pre>
     *跳跃
     * </pre>
     *
     * <code>required int32 jump = 5;</code>
     * @return Whether the jump field is set.
     */
    public boolean hasJump() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     *跳跃
     * </pre>
     *
     * <code>required int32 jump = 5;</code>
     * @return The jump.
     */
    public int getJump() {
      return jump_;
    }

    public static final int JUMPLEVEL_FIELD_NUMBER = 6;
    private int jumpLevel_;
    /**
     * <pre>
     *跳跃段数
     * </pre>
     *
     * <code>required int32 jumpLevel = 6;</code>
     * @return Whether the jumpLevel field is set.
     */
    public boolean hasJumpLevel() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     *跳跃段数
     * </pre>
     *
     * <code>required int32 jumpLevel = 6;</code>
     * @return The jumpLevel.
     */
    public int getJumpLevel() {
      return jumpLevel_;
    }

    public static final int ADVERTID_FIELD_NUMBER = 7;
    private int advertId_;
    /**
     * <pre>
     *广告id
     * </pre>
     *
     * <code>required int32 advertId = 7;</code>
     * @return Whether the advertId field is set.
     */
    public boolean hasAdvertId() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     *广告id
     * </pre>
     *
     * <code>required int32 advertId = 7;</code>
     * @return The advertId.
     */
    public int getAdvertId() {
      return advertId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasScore()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCheckPoint()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMultiple()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasJump()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasJumpLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAdvertId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, type_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, score_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, checkPoint_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(4, multiple_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt32(5, jump_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeInt32(6, jumpLevel_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeInt32(7, advertId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, score_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, checkPoint_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, multiple_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, jump_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, jumpLevel_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, advertId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.BattleProto.BattleSettleReq)) {
        return super.equals(obj);
      }
      proto.BattleProto.BattleSettleReq other = (proto.BattleProto.BattleSettleReq) obj;

      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (getType()
            != other.getType()) return false;
      }
      if (hasScore() != other.hasScore()) return false;
      if (hasScore()) {
        if (getScore()
            != other.getScore()) return false;
      }
      if (hasCheckPoint() != other.hasCheckPoint()) return false;
      if (hasCheckPoint()) {
        if (getCheckPoint()
            != other.getCheckPoint()) return false;
      }
      if (hasMultiple() != other.hasMultiple()) return false;
      if (hasMultiple()) {
        if (getMultiple()
            != other.getMultiple()) return false;
      }
      if (hasJump() != other.hasJump()) return false;
      if (hasJump()) {
        if (getJump()
            != other.getJump()) return false;
      }
      if (hasJumpLevel() != other.hasJumpLevel()) return false;
      if (hasJumpLevel()) {
        if (getJumpLevel()
            != other.getJumpLevel()) return false;
      }
      if (hasAdvertId() != other.hasAdvertId()) return false;
      if (hasAdvertId()) {
        if (getAdvertId()
            != other.getAdvertId()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType();
      }
      if (hasScore()) {
        hash = (37 * hash) + SCORE_FIELD_NUMBER;
        hash = (53 * hash) + getScore();
      }
      if (hasCheckPoint()) {
        hash = (37 * hash) + CHECKPOINT_FIELD_NUMBER;
        hash = (53 * hash) + getCheckPoint();
      }
      if (hasMultiple()) {
        hash = (37 * hash) + MULTIPLE_FIELD_NUMBER;
        hash = (53 * hash) + getMultiple();
      }
      if (hasJump()) {
        hash = (37 * hash) + JUMP_FIELD_NUMBER;
        hash = (53 * hash) + getJump();
      }
      if (hasJumpLevel()) {
        hash = (37 * hash) + JUMPLEVEL_FIELD_NUMBER;
        hash = (53 * hash) + getJumpLevel();
      }
      if (hasAdvertId()) {
        hash = (37 * hash) + ADVERTID_FIELD_NUMBER;
        hash = (53 * hash) + getAdvertId();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.BattleProto.BattleSettleReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.BattleProto.BattleSettleReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.BattleProto.BattleSettleReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.BattleProto.BattleSettleReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.BattleProto.BattleSettleReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.BattleProto.BattleSettleReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.BattleProto.BattleSettleReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.BattleProto.BattleSettleReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.BattleProto.BattleSettleReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.BattleProto.BattleSettleReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.BattleProto.BattleSettleReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.BattleProto.BattleSettleReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.BattleProto.BattleSettleReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *战斗结算
     *cmd:1010
     * </pre>
     *
     * Protobuf type {@code BattleSettleReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BattleSettleReq)
        proto.BattleProto.BattleSettleReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.BattleProto.internal_static_BattleSettleReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.BattleProto.internal_static_BattleSettleReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.BattleProto.BattleSettleReq.class, proto.BattleProto.BattleSettleReq.Builder.class);
      }

      // Construct using proto.BattleProto.BattleSettleReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        score_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        checkPoint_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        multiple_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        jump_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        jumpLevel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        advertId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.BattleProto.internal_static_BattleSettleReq_descriptor;
      }

      @java.lang.Override
      public proto.BattleProto.BattleSettleReq getDefaultInstanceForType() {
        return proto.BattleProto.BattleSettleReq.getDefaultInstance();
      }

      @java.lang.Override
      public proto.BattleProto.BattleSettleReq build() {
        proto.BattleProto.BattleSettleReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.BattleProto.BattleSettleReq buildPartial() {
        proto.BattleProto.BattleSettleReq result = new proto.BattleProto.BattleSettleReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.type_ = type_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.score_ = score_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.checkPoint_ = checkPoint_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.multiple_ = multiple_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.jump_ = jump_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.jumpLevel_ = jumpLevel_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.advertId_ = advertId_;
          to_bitField0_ |= 0x00000040;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.BattleProto.BattleSettleReq) {
          return mergeFrom((proto.BattleProto.BattleSettleReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.BattleProto.BattleSettleReq other) {
        if (other == proto.BattleProto.BattleSettleReq.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasScore()) {
          setScore(other.getScore());
        }
        if (other.hasCheckPoint()) {
          setCheckPoint(other.getCheckPoint());
        }
        if (other.hasMultiple()) {
          setMultiple(other.getMultiple());
        }
        if (other.hasJump()) {
          setJump(other.getJump());
        }
        if (other.hasJumpLevel()) {
          setJumpLevel(other.getJumpLevel());
        }
        if (other.hasAdvertId()) {
          setAdvertId(other.getAdvertId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasType()) {
          return false;
        }
        if (!hasScore()) {
          return false;
        }
        if (!hasCheckPoint()) {
          return false;
        }
        if (!hasMultiple()) {
          return false;
        }
        if (!hasJump()) {
          return false;
        }
        if (!hasJumpLevel()) {
          return false;
        }
        if (!hasAdvertId()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.BattleProto.BattleSettleReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.BattleProto.BattleSettleReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ ;
      /**
       * <pre>
       *1：竞标赛 2：经典模式
       * </pre>
       *
       * <code>required int32 type = 1;</code>
       * @return Whether the type field is set.
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *1：竞标赛 2：经典模式
       * </pre>
       *
       * <code>required int32 type = 1;</code>
       * @return The type.
       */
      public int getType() {
        return type_;
      }
      /**
       * <pre>
       *1：竞标赛 2：经典模式
       * </pre>
       *
       * <code>required int32 type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *1：竞标赛 2：经典模式
       * </pre>
       *
       * <code>required int32 type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      private int score_ ;
      /**
       * <pre>
       *本局积分
       * </pre>
       *
       * <code>required int32 score = 2;</code>
       * @return Whether the score field is set.
       */
      public boolean hasScore() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       *本局积分
       * </pre>
       *
       * <code>required int32 score = 2;</code>
       * @return The score.
       */
      public int getScore() {
        return score_;
      }
      /**
       * <pre>
       *本局积分
       * </pre>
       *
       * <code>required int32 score = 2;</code>
       * @param value The score to set.
       * @return This builder for chaining.
       */
      public Builder setScore(int value) {
        bitField0_ |= 0x00000002;
        score_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *本局积分
       * </pre>
       *
       * <code>required int32 score = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearScore() {
        bitField0_ = (bitField0_ & ~0x00000002);
        score_ = 0;
        onChanged();
        return this;
      }

      private int checkPoint_ ;
      /**
       * <pre>
       *本局关卡
       * </pre>
       *
       * <code>required int32 checkPoint = 3;</code>
       * @return Whether the checkPoint field is set.
       */
      public boolean hasCheckPoint() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       *本局关卡
       * </pre>
       *
       * <code>required int32 checkPoint = 3;</code>
       * @return The checkPoint.
       */
      public int getCheckPoint() {
        return checkPoint_;
      }
      /**
       * <pre>
       *本局关卡
       * </pre>
       *
       * <code>required int32 checkPoint = 3;</code>
       * @param value The checkPoint to set.
       * @return This builder for chaining.
       */
      public Builder setCheckPoint(int value) {
        bitField0_ |= 0x00000004;
        checkPoint_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *本局关卡
       * </pre>
       *
       * <code>required int32 checkPoint = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCheckPoint() {
        bitField0_ = (bitField0_ & ~0x00000004);
        checkPoint_ = 0;
        onChanged();
        return this;
      }

      private int multiple_ ;
      /**
       * <pre>
       *倍数
       * </pre>
       *
       * <code>required int32 multiple = 4;</code>
       * @return Whether the multiple field is set.
       */
      public boolean hasMultiple() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       *倍数
       * </pre>
       *
       * <code>required int32 multiple = 4;</code>
       * @return The multiple.
       */
      public int getMultiple() {
        return multiple_;
      }
      /**
       * <pre>
       *倍数
       * </pre>
       *
       * <code>required int32 multiple = 4;</code>
       * @param value The multiple to set.
       * @return This builder for chaining.
       */
      public Builder setMultiple(int value) {
        bitField0_ |= 0x00000008;
        multiple_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *倍数
       * </pre>
       *
       * <code>required int32 multiple = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMultiple() {
        bitField0_ = (bitField0_ & ~0x00000008);
        multiple_ = 0;
        onChanged();
        return this;
      }

      private int jump_ ;
      /**
       * <pre>
       *跳跃
       * </pre>
       *
       * <code>required int32 jump = 5;</code>
       * @return Whether the jump field is set.
       */
      public boolean hasJump() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <pre>
       *跳跃
       * </pre>
       *
       * <code>required int32 jump = 5;</code>
       * @return The jump.
       */
      public int getJump() {
        return jump_;
      }
      /**
       * <pre>
       *跳跃
       * </pre>
       *
       * <code>required int32 jump = 5;</code>
       * @param value The jump to set.
       * @return This builder for chaining.
       */
      public Builder setJump(int value) {
        bitField0_ |= 0x00000010;
        jump_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *跳跃
       * </pre>
       *
       * <code>required int32 jump = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearJump() {
        bitField0_ = (bitField0_ & ~0x00000010);
        jump_ = 0;
        onChanged();
        return this;
      }

      private int jumpLevel_ ;
      /**
       * <pre>
       *跳跃段数
       * </pre>
       *
       * <code>required int32 jumpLevel = 6;</code>
       * @return Whether the jumpLevel field is set.
       */
      public boolean hasJumpLevel() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <pre>
       *跳跃段数
       * </pre>
       *
       * <code>required int32 jumpLevel = 6;</code>
       * @return The jumpLevel.
       */
      public int getJumpLevel() {
        return jumpLevel_;
      }
      /**
       * <pre>
       *跳跃段数
       * </pre>
       *
       * <code>required int32 jumpLevel = 6;</code>
       * @param value The jumpLevel to set.
       * @return This builder for chaining.
       */
      public Builder setJumpLevel(int value) {
        bitField0_ |= 0x00000020;
        jumpLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *跳跃段数
       * </pre>
       *
       * <code>required int32 jumpLevel = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearJumpLevel() {
        bitField0_ = (bitField0_ & ~0x00000020);
        jumpLevel_ = 0;
        onChanged();
        return this;
      }

      private int advertId_ ;
      /**
       * <pre>
       *广告id
       * </pre>
       *
       * <code>required int32 advertId = 7;</code>
       * @return Whether the advertId field is set.
       */
      public boolean hasAdvertId() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <pre>
       *广告id
       * </pre>
       *
       * <code>required int32 advertId = 7;</code>
       * @return The advertId.
       */
      public int getAdvertId() {
        return advertId_;
      }
      /**
       * <pre>
       *广告id
       * </pre>
       *
       * <code>required int32 advertId = 7;</code>
       * @param value The advertId to set.
       * @return This builder for chaining.
       */
      public Builder setAdvertId(int value) {
        bitField0_ |= 0x00000040;
        advertId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *广告id
       * </pre>
       *
       * <code>required int32 advertId = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearAdvertId() {
        bitField0_ = (bitField0_ & ~0x00000040);
        advertId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BattleSettleReq)
    }

    // @@protoc_insertion_point(class_scope:BattleSettleReq)
    private static final proto.BattleProto.BattleSettleReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.BattleProto.BattleSettleReq();
    }

    public static proto.BattleProto.BattleSettleReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<BattleSettleReq>
        PARSER = new com.google.protobuf.AbstractParser<BattleSettleReq>() {
      @java.lang.Override
      public BattleSettleReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BattleSettleReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BattleSettleReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BattleSettleReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.BattleProto.BattleSettleReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BattleSettleRspOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BattleSettleRsp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *是否成功;
     * </pre>
     *
     * <code>required bool isSucc = 1;</code>
     * @return Whether the isSucc field is set.
     */
    boolean hasIsSucc();
    /**
     * <pre>
     *是否成功;
     * </pre>
     *
     * <code>required bool isSucc = 1;</code>
     * @return The isSucc.
     */
    boolean getIsSucc();

    /**
     * <pre>
     *错误信息;
     * </pre>
     *
     * <code>optional string errMess = 2;</code>
     * @return Whether the errMess field is set.
     */
    boolean hasErrMess();
    /**
     * <pre>
     *错误信息;
     * </pre>
     *
     * <code>optional string errMess = 2;</code>
     * @return The errMess.
     */
    java.lang.String getErrMess();
    /**
     * <pre>
     *错误信息;
     * </pre>
     *
     * <code>optional string errMess = 2;</code>
     * @return The bytes for errMess.
     */
    com.google.protobuf.ByteString
        getErrMessBytes();

    /**
     * <pre>
     *奖励资源
     * </pre>
     *
     * <code>repeated .ResourcesPt resp = 3;</code>
     */
    java.util.List<proto.BaseProto.ResourcesPt> 
        getRespList();
    /**
     * <pre>
     *奖励资源
     * </pre>
     *
     * <code>repeated .ResourcesPt resp = 3;</code>
     */
    proto.BaseProto.ResourcesPt getResp(int index);
    /**
     * <pre>
     *奖励资源
     * </pre>
     *
     * <code>repeated .ResourcesPt resp = 3;</code>
     */
    int getRespCount();
    /**
     * <pre>
     *奖励资源
     * </pre>
     *
     * <code>repeated .ResourcesPt resp = 3;</code>
     */
    java.util.List<? extends proto.BaseProto.ResourcesPtOrBuilder> 
        getRespOrBuilderList();
    /**
     * <pre>
     *奖励资源
     * </pre>
     *
     * <code>repeated .ResourcesPt resp = 3;</code>
     */
    proto.BaseProto.ResourcesPtOrBuilder getRespOrBuilder(
        int index);
  }
  /**
   * <pre>
   *房间战斗结算
   *cmd:5010
   * </pre>
   *
   * Protobuf type {@code BattleSettleRsp}
   */
  public  static final class BattleSettleRsp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BattleSettleRsp)
      BattleSettleRspOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BattleSettleRsp.newBuilder() to construct.
    private BattleSettleRsp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BattleSettleRsp() {
      errMess_ = "";
      resp_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BattleSettleRsp();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BattleSettleRsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              isSucc_ = input.readBool();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              errMess_ = bs;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                resp_ = new java.util.ArrayList<proto.BaseProto.ResourcesPt>();
                mutable_bitField0_ |= 0x00000004;
              }
              resp_.add(
                  input.readMessage(proto.BaseProto.ResourcesPt.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) != 0)) {
          resp_ = java.util.Collections.unmodifiableList(resp_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.BattleProto.internal_static_BattleSettleRsp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.BattleProto.internal_static_BattleSettleRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.BattleProto.BattleSettleRsp.class, proto.BattleProto.BattleSettleRsp.Builder.class);
    }

    private int bitField0_;
    public static final int ISSUCC_FIELD_NUMBER = 1;
    private boolean isSucc_;
    /**
     * <pre>
     *是否成功;
     * </pre>
     *
     * <code>required bool isSucc = 1;</code>
     * @return Whether the isSucc field is set.
     */
    public boolean hasIsSucc() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *是否成功;
     * </pre>
     *
     * <code>required bool isSucc = 1;</code>
     * @return The isSucc.
     */
    public boolean getIsSucc() {
      return isSucc_;
    }

    public static final int ERRMESS_FIELD_NUMBER = 2;
    private volatile java.lang.Object errMess_;
    /**
     * <pre>
     *错误信息;
     * </pre>
     *
     * <code>optional string errMess = 2;</code>
     * @return Whether the errMess field is set.
     */
    public boolean hasErrMess() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     *错误信息;
     * </pre>
     *
     * <code>optional string errMess = 2;</code>
     * @return The errMess.
     */
    public java.lang.String getErrMess() {
      java.lang.Object ref = errMess_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errMess_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *错误信息;
     * </pre>
     *
     * <code>optional string errMess = 2;</code>
     * @return The bytes for errMess.
     */
    public com.google.protobuf.ByteString
        getErrMessBytes() {
      java.lang.Object ref = errMess_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errMess_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESP_FIELD_NUMBER = 3;
    private java.util.List<proto.BaseProto.ResourcesPt> resp_;
    /**
     * <pre>
     *奖励资源
     * </pre>
     *
     * <code>repeated .ResourcesPt resp = 3;</code>
     */
    public java.util.List<proto.BaseProto.ResourcesPt> getRespList() {
      return resp_;
    }
    /**
     * <pre>
     *奖励资源
     * </pre>
     *
     * <code>repeated .ResourcesPt resp = 3;</code>
     */
    public java.util.List<? extends proto.BaseProto.ResourcesPtOrBuilder> 
        getRespOrBuilderList() {
      return resp_;
    }
    /**
     * <pre>
     *奖励资源
     * </pre>
     *
     * <code>repeated .ResourcesPt resp = 3;</code>
     */
    public int getRespCount() {
      return resp_.size();
    }
    /**
     * <pre>
     *奖励资源
     * </pre>
     *
     * <code>repeated .ResourcesPt resp = 3;</code>
     */
    public proto.BaseProto.ResourcesPt getResp(int index) {
      return resp_.get(index);
    }
    /**
     * <pre>
     *奖励资源
     * </pre>
     *
     * <code>repeated .ResourcesPt resp = 3;</code>
     */
    public proto.BaseProto.ResourcesPtOrBuilder getRespOrBuilder(
        int index) {
      return resp_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasIsSucc()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getRespCount(); i++) {
        if (!getResp(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBool(1, isSucc_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errMess_);
      }
      for (int i = 0; i < resp_.size(); i++) {
        output.writeMessage(3, resp_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isSucc_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, errMess_);
      }
      for (int i = 0; i < resp_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, resp_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.BattleProto.BattleSettleRsp)) {
        return super.equals(obj);
      }
      proto.BattleProto.BattleSettleRsp other = (proto.BattleProto.BattleSettleRsp) obj;

      if (hasIsSucc() != other.hasIsSucc()) return false;
      if (hasIsSucc()) {
        if (getIsSucc()
            != other.getIsSucc()) return false;
      }
      if (hasErrMess() != other.hasErrMess()) return false;
      if (hasErrMess()) {
        if (!getErrMess()
            .equals(other.getErrMess())) return false;
      }
      if (!getRespList()
          .equals(other.getRespList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasIsSucc()) {
        hash = (37 * hash) + ISSUCC_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIsSucc());
      }
      if (hasErrMess()) {
        hash = (37 * hash) + ERRMESS_FIELD_NUMBER;
        hash = (53 * hash) + getErrMess().hashCode();
      }
      if (getRespCount() > 0) {
        hash = (37 * hash) + RESP_FIELD_NUMBER;
        hash = (53 * hash) + getRespList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.BattleProto.BattleSettleRsp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.BattleProto.BattleSettleRsp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.BattleProto.BattleSettleRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.BattleProto.BattleSettleRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.BattleProto.BattleSettleRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.BattleProto.BattleSettleRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.BattleProto.BattleSettleRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.BattleProto.BattleSettleRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.BattleProto.BattleSettleRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.BattleProto.BattleSettleRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.BattleProto.BattleSettleRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.BattleProto.BattleSettleRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.BattleProto.BattleSettleRsp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *房间战斗结算
     *cmd:5010
     * </pre>
     *
     * Protobuf type {@code BattleSettleRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BattleSettleRsp)
        proto.BattleProto.BattleSettleRspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.BattleProto.internal_static_BattleSettleRsp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.BattleProto.internal_static_BattleSettleRsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.BattleProto.BattleSettleRsp.class, proto.BattleProto.BattleSettleRsp.Builder.class);
      }

      // Construct using proto.BattleProto.BattleSettleRsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRespFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        isSucc_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        errMess_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (respBuilder_ == null) {
          resp_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          respBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.BattleProto.internal_static_BattleSettleRsp_descriptor;
      }

      @java.lang.Override
      public proto.BattleProto.BattleSettleRsp getDefaultInstanceForType() {
        return proto.BattleProto.BattleSettleRsp.getDefaultInstance();
      }

      @java.lang.Override
      public proto.BattleProto.BattleSettleRsp build() {
        proto.BattleProto.BattleSettleRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.BattleProto.BattleSettleRsp buildPartial() {
        proto.BattleProto.BattleSettleRsp result = new proto.BattleProto.BattleSettleRsp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.isSucc_ = isSucc_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.errMess_ = errMess_;
        if (respBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0)) {
            resp_ = java.util.Collections.unmodifiableList(resp_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.resp_ = resp_;
        } else {
          result.resp_ = respBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.BattleProto.BattleSettleRsp) {
          return mergeFrom((proto.BattleProto.BattleSettleRsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.BattleProto.BattleSettleRsp other) {
        if (other == proto.BattleProto.BattleSettleRsp.getDefaultInstance()) return this;
        if (other.hasIsSucc()) {
          setIsSucc(other.getIsSucc());
        }
        if (other.hasErrMess()) {
          bitField0_ |= 0x00000002;
          errMess_ = other.errMess_;
          onChanged();
        }
        if (respBuilder_ == null) {
          if (!other.resp_.isEmpty()) {
            if (resp_.isEmpty()) {
              resp_ = other.resp_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureRespIsMutable();
              resp_.addAll(other.resp_);
            }
            onChanged();
          }
        } else {
          if (!other.resp_.isEmpty()) {
            if (respBuilder_.isEmpty()) {
              respBuilder_.dispose();
              respBuilder_ = null;
              resp_ = other.resp_;
              bitField0_ = (bitField0_ & ~0x00000004);
              respBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRespFieldBuilder() : null;
            } else {
              respBuilder_.addAllMessages(other.resp_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasIsSucc()) {
          return false;
        }
        for (int i = 0; i < getRespCount(); i++) {
          if (!getResp(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.BattleProto.BattleSettleRsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.BattleProto.BattleSettleRsp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean isSucc_ ;
      /**
       * <pre>
       *是否成功;
       * </pre>
       *
       * <code>required bool isSucc = 1;</code>
       * @return Whether the isSucc field is set.
       */
      public boolean hasIsSucc() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *是否成功;
       * </pre>
       *
       * <code>required bool isSucc = 1;</code>
       * @return The isSucc.
       */
      public boolean getIsSucc() {
        return isSucc_;
      }
      /**
       * <pre>
       *是否成功;
       * </pre>
       *
       * <code>required bool isSucc = 1;</code>
       * @param value The isSucc to set.
       * @return This builder for chaining.
       */
      public Builder setIsSucc(boolean value) {
        bitField0_ |= 0x00000001;
        isSucc_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否成功;
       * </pre>
       *
       * <code>required bool isSucc = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsSucc() {
        bitField0_ = (bitField0_ & ~0x00000001);
        isSucc_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object errMess_ = "";
      /**
       * <pre>
       *错误信息;
       * </pre>
       *
       * <code>optional string errMess = 2;</code>
       * @return Whether the errMess field is set.
       */
      public boolean hasErrMess() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       *错误信息;
       * </pre>
       *
       * <code>optional string errMess = 2;</code>
       * @return The errMess.
       */
      public java.lang.String getErrMess() {
        java.lang.Object ref = errMess_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            errMess_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *错误信息;
       * </pre>
       *
       * <code>optional string errMess = 2;</code>
       * @return The bytes for errMess.
       */
      public com.google.protobuf.ByteString
          getErrMessBytes() {
        java.lang.Object ref = errMess_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errMess_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *错误信息;
       * </pre>
       *
       * <code>optional string errMess = 2;</code>
       * @param value The errMess to set.
       * @return This builder for chaining.
       */
      public Builder setErrMess(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errMess_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *错误信息;
       * </pre>
       *
       * <code>optional string errMess = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrMess() {
        bitField0_ = (bitField0_ & ~0x00000002);
        errMess_ = getDefaultInstance().getErrMess();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *错误信息;
       * </pre>
       *
       * <code>optional string errMess = 2;</code>
       * @param value The bytes for errMess to set.
       * @return This builder for chaining.
       */
      public Builder setErrMessBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errMess_ = value;
        onChanged();
        return this;
      }

      private java.util.List<proto.BaseProto.ResourcesPt> resp_ =
        java.util.Collections.emptyList();
      private void ensureRespIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          resp_ = new java.util.ArrayList<proto.BaseProto.ResourcesPt>(resp_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.BaseProto.ResourcesPt, proto.BaseProto.ResourcesPt.Builder, proto.BaseProto.ResourcesPtOrBuilder> respBuilder_;

      /**
       * <pre>
       *奖励资源
       * </pre>
       *
       * <code>repeated .ResourcesPt resp = 3;</code>
       */
      public java.util.List<proto.BaseProto.ResourcesPt> getRespList() {
        if (respBuilder_ == null) {
          return java.util.Collections.unmodifiableList(resp_);
        } else {
          return respBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *奖励资源
       * </pre>
       *
       * <code>repeated .ResourcesPt resp = 3;</code>
       */
      public int getRespCount() {
        if (respBuilder_ == null) {
          return resp_.size();
        } else {
          return respBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *奖励资源
       * </pre>
       *
       * <code>repeated .ResourcesPt resp = 3;</code>
       */
      public proto.BaseProto.ResourcesPt getResp(int index) {
        if (respBuilder_ == null) {
          return resp_.get(index);
        } else {
          return respBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *奖励资源
       * </pre>
       *
       * <code>repeated .ResourcesPt resp = 3;</code>
       */
      public Builder setResp(
          int index, proto.BaseProto.ResourcesPt value) {
        if (respBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRespIsMutable();
          resp_.set(index, value);
          onChanged();
        } else {
          respBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *奖励资源
       * </pre>
       *
       * <code>repeated .ResourcesPt resp = 3;</code>
       */
      public Builder setResp(
          int index, proto.BaseProto.ResourcesPt.Builder builderForValue) {
        if (respBuilder_ == null) {
          ensureRespIsMutable();
          resp_.set(index, builderForValue.build());
          onChanged();
        } else {
          respBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *奖励资源
       * </pre>
       *
       * <code>repeated .ResourcesPt resp = 3;</code>
       */
      public Builder addResp(proto.BaseProto.ResourcesPt value) {
        if (respBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRespIsMutable();
          resp_.add(value);
          onChanged();
        } else {
          respBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *奖励资源
       * </pre>
       *
       * <code>repeated .ResourcesPt resp = 3;</code>
       */
      public Builder addResp(
          int index, proto.BaseProto.ResourcesPt value) {
        if (respBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRespIsMutable();
          resp_.add(index, value);
          onChanged();
        } else {
          respBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *奖励资源
       * </pre>
       *
       * <code>repeated .ResourcesPt resp = 3;</code>
       */
      public Builder addResp(
          proto.BaseProto.ResourcesPt.Builder builderForValue) {
        if (respBuilder_ == null) {
          ensureRespIsMutable();
          resp_.add(builderForValue.build());
          onChanged();
        } else {
          respBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *奖励资源
       * </pre>
       *
       * <code>repeated .ResourcesPt resp = 3;</code>
       */
      public Builder addResp(
          int index, proto.BaseProto.ResourcesPt.Builder builderForValue) {
        if (respBuilder_ == null) {
          ensureRespIsMutable();
          resp_.add(index, builderForValue.build());
          onChanged();
        } else {
          respBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *奖励资源
       * </pre>
       *
       * <code>repeated .ResourcesPt resp = 3;</code>
       */
      public Builder addAllResp(
          java.lang.Iterable<? extends proto.BaseProto.ResourcesPt> values) {
        if (respBuilder_ == null) {
          ensureRespIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, resp_);
          onChanged();
        } else {
          respBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *奖励资源
       * </pre>
       *
       * <code>repeated .ResourcesPt resp = 3;</code>
       */
      public Builder clearResp() {
        if (respBuilder_ == null) {
          resp_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          respBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *奖励资源
       * </pre>
       *
       * <code>repeated .ResourcesPt resp = 3;</code>
       */
      public Builder removeResp(int index) {
        if (respBuilder_ == null) {
          ensureRespIsMutable();
          resp_.remove(index);
          onChanged();
        } else {
          respBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *奖励资源
       * </pre>
       *
       * <code>repeated .ResourcesPt resp = 3;</code>
       */
      public proto.BaseProto.ResourcesPt.Builder getRespBuilder(
          int index) {
        return getRespFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *奖励资源
       * </pre>
       *
       * <code>repeated .ResourcesPt resp = 3;</code>
       */
      public proto.BaseProto.ResourcesPtOrBuilder getRespOrBuilder(
          int index) {
        if (respBuilder_ == null) {
          return resp_.get(index);  } else {
          return respBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *奖励资源
       * </pre>
       *
       * <code>repeated .ResourcesPt resp = 3;</code>
       */
      public java.util.List<? extends proto.BaseProto.ResourcesPtOrBuilder> 
           getRespOrBuilderList() {
        if (respBuilder_ != null) {
          return respBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(resp_);
        }
      }
      /**
       * <pre>
       *奖励资源
       * </pre>
       *
       * <code>repeated .ResourcesPt resp = 3;</code>
       */
      public proto.BaseProto.ResourcesPt.Builder addRespBuilder() {
        return getRespFieldBuilder().addBuilder(
            proto.BaseProto.ResourcesPt.getDefaultInstance());
      }
      /**
       * <pre>
       *奖励资源
       * </pre>
       *
       * <code>repeated .ResourcesPt resp = 3;</code>
       */
      public proto.BaseProto.ResourcesPt.Builder addRespBuilder(
          int index) {
        return getRespFieldBuilder().addBuilder(
            index, proto.BaseProto.ResourcesPt.getDefaultInstance());
      }
      /**
       * <pre>
       *奖励资源
       * </pre>
       *
       * <code>repeated .ResourcesPt resp = 3;</code>
       */
      public java.util.List<proto.BaseProto.ResourcesPt.Builder> 
           getRespBuilderList() {
        return getRespFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.BaseProto.ResourcesPt, proto.BaseProto.ResourcesPt.Builder, proto.BaseProto.ResourcesPtOrBuilder> 
          getRespFieldBuilder() {
        if (respBuilder_ == null) {
          respBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              proto.BaseProto.ResourcesPt, proto.BaseProto.ResourcesPt.Builder, proto.BaseProto.ResourcesPtOrBuilder>(
                  resp_,
                  ((bitField0_ & 0x00000004) != 0),
                  getParentForChildren(),
                  isClean());
          resp_ = null;
        }
        return respBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BattleSettleRsp)
    }

    // @@protoc_insertion_point(class_scope:BattleSettleRsp)
    private static final proto.BattleProto.BattleSettleRsp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.BattleProto.BattleSettleRsp();
    }

    public static proto.BattleProto.BattleSettleRsp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<BattleSettleRsp>
        PARSER = new com.google.protobuf.AbstractParser<BattleSettleRsp>() {
      @java.lang.Override
      public BattleSettleRsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BattleSettleRsp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BattleSettleRsp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BattleSettleRsp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.BattleProto.BattleSettleRsp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BattleSettleReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BattleSettleReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BattleSettleRsp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BattleSettleRsp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014battle.proto\032\nbase.proto\"\207\001\n\017BattleSet" +
      "tleReq\022\014\n\004type\030\001 \002(\005\022\r\n\005score\030\002 \002(\005\022\022\n\nc" +
      "heckPoint\030\003 \002(\005\022\020\n\010multiple\030\004 \002(\005\022\014\n\004jum" +
      "p\030\005 \002(\005\022\021\n\tjumpLevel\030\006 \002(\005\022\020\n\010advertId\030\007" +
      " \002(\005\"N\n\017BattleSettleRsp\022\016\n\006isSucc\030\001 \002(\010\022" +
      "\017\n\007errMess\030\002 \001(\t\022\032\n\004resp\030\003 \003(\0132\014.Resourc" +
      "esPtB\026\n\005protoB\013BattleProtoP\000"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          proto.BaseProto.getDescriptor(),
        });
    internal_static_BattleSettleReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BattleSettleReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BattleSettleReq_descriptor,
        new java.lang.String[] { "Type", "Score", "CheckPoint", "Multiple", "Jump", "JumpLevel", "AdvertId", });
    internal_static_BattleSettleRsp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BattleSettleRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BattleSettleRsp_descriptor,
        new java.lang.String[] { "IsSucc", "ErrMess", "Resp", });
    proto.BaseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
