// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: buff.proto

package proto;

public final class BuffProto {
  private BuffProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BuffReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BuffReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *buffId
     * </pre>
     *
     * <code>required int32 buffId = 1;</code>
     */
    boolean hasBuffId();
    /**
     * <pre>
     *buffId
     * </pre>
     *
     * <code>required int32 buffId = 1;</code>
     */
    int getBuffId();
  }
  /**
   * <pre>
   * buff请求
   *cmd:1011
   * </pre>
   *
   * Protobuf type {@code BuffReq}
   */
  public  static final class BuffReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BuffReq)
      BuffReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BuffReq.newBuilder() to construct.
    private BuffReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BuffReq() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BuffReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              buffId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.BuffProto.internal_static_BuffReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.BuffProto.internal_static_BuffReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.BuffProto.BuffReq.class, proto.BuffProto.BuffReq.Builder.class);
    }

    private int bitField0_;
    public static final int BUFFID_FIELD_NUMBER = 1;
    private int buffId_;
    /**
     * <pre>
     *buffId
     * </pre>
     *
     * <code>required int32 buffId = 1;</code>
     */
    public boolean hasBuffId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *buffId
     * </pre>
     *
     * <code>required int32 buffId = 1;</code>
     */
    public int getBuffId() {
      return buffId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasBuffId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, buffId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, buffId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.BuffProto.BuffReq)) {
        return super.equals(obj);
      }
      proto.BuffProto.BuffReq other = (proto.BuffProto.BuffReq) obj;

      if (hasBuffId() != other.hasBuffId()) return false;
      if (hasBuffId()) {
        if (getBuffId()
            != other.getBuffId()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasBuffId()) {
        hash = (37 * hash) + BUFFID_FIELD_NUMBER;
        hash = (53 * hash) + getBuffId();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.BuffProto.BuffReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.BuffProto.BuffReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.BuffProto.BuffReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.BuffProto.BuffReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.BuffProto.BuffReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.BuffProto.BuffReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.BuffProto.BuffReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.BuffProto.BuffReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.BuffProto.BuffReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.BuffProto.BuffReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.BuffProto.BuffReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.BuffProto.BuffReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.BuffProto.BuffReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * buff请求
     *cmd:1011
     * </pre>
     *
     * Protobuf type {@code BuffReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BuffReq)
        proto.BuffProto.BuffReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.BuffProto.internal_static_BuffReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.BuffProto.internal_static_BuffReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.BuffProto.BuffReq.class, proto.BuffProto.BuffReq.Builder.class);
      }

      // Construct using proto.BuffProto.BuffReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        buffId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.BuffProto.internal_static_BuffReq_descriptor;
      }

      @java.lang.Override
      public proto.BuffProto.BuffReq getDefaultInstanceForType() {
        return proto.BuffProto.BuffReq.getDefaultInstance();
      }

      @java.lang.Override
      public proto.BuffProto.BuffReq build() {
        proto.BuffProto.BuffReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.BuffProto.BuffReq buildPartial() {
        proto.BuffProto.BuffReq result = new proto.BuffProto.BuffReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.buffId_ = buffId_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.BuffProto.BuffReq) {
          return mergeFrom((proto.BuffProto.BuffReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.BuffProto.BuffReq other) {
        if (other == proto.BuffProto.BuffReq.getDefaultInstance()) return this;
        if (other.hasBuffId()) {
          setBuffId(other.getBuffId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasBuffId()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.BuffProto.BuffReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.BuffProto.BuffReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int buffId_ ;
      /**
       * <pre>
       *buffId
       * </pre>
       *
       * <code>required int32 buffId = 1;</code>
       */
      public boolean hasBuffId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *buffId
       * </pre>
       *
       * <code>required int32 buffId = 1;</code>
       */
      public int getBuffId() {
        return buffId_;
      }
      /**
       * <pre>
       *buffId
       * </pre>
       *
       * <code>required int32 buffId = 1;</code>
       */
      public Builder setBuffId(int value) {
        bitField0_ |= 0x00000001;
        buffId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *buffId
       * </pre>
       *
       * <code>required int32 buffId = 1;</code>
       */
      public Builder clearBuffId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        buffId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BuffReq)
    }

    // @@protoc_insertion_point(class_scope:BuffReq)
    private static final proto.BuffProto.BuffReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.BuffProto.BuffReq();
    }

    public static proto.BuffProto.BuffReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<BuffReq>
        PARSER = new com.google.protobuf.AbstractParser<BuffReq>() {
      @java.lang.Override
      public BuffReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BuffReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BuffReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BuffReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.BuffProto.BuffReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BuffRspOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BuffRsp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *是否成功;
     * </pre>
     *
     * <code>required bool isSucc = 1;</code>
     */
    boolean hasIsSucc();
    /**
     * <pre>
     *是否成功;
     * </pre>
     *
     * <code>required bool isSucc = 1;</code>
     */
    boolean getIsSucc();

    /**
     * <pre>
     *错误信息;
     * </pre>
     *
     * <code>optional string errMess = 2;</code>
     */
    boolean hasErrMess();
    /**
     * <pre>
     *错误信息;
     * </pre>
     *
     * <code>optional string errMess = 2;</code>
     */
    java.lang.String getErrMess();
    /**
     * <pre>
     *错误信息;
     * </pre>
     *
     * <code>optional string errMess = 2;</code>
     */
    com.google.protobuf.ByteString
        getErrMessBytes();

    /**
     * <pre>
     *buff数据
     * </pre>
     *
     * <code>optional .BuffPt buff = 3;</code>
     */
    boolean hasBuff();
    /**
     * <pre>
     *buff数据
     * </pre>
     *
     * <code>optional .BuffPt buff = 3;</code>
     */
    proto.BaseProto.BuffPt getBuff();
    /**
     * <pre>
     *buff数据
     * </pre>
     *
     * <code>optional .BuffPt buff = 3;</code>
     */
    proto.BaseProto.BuffPtOrBuilder getBuffOrBuilder();
  }
  /**
   * <pre>
   * buff返回
   *cmd:5011
   * </pre>
   *
   * Protobuf type {@code BuffRsp}
   */
  public  static final class BuffRsp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BuffRsp)
      BuffRspOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BuffRsp.newBuilder() to construct.
    private BuffRsp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BuffRsp() {
      errMess_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BuffRsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              isSucc_ = input.readBool();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              errMess_ = bs;
              break;
            }
            case 26: {
              proto.BaseProto.BuffPt.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) != 0)) {
                subBuilder = buff_.toBuilder();
              }
              buff_ = input.readMessage(proto.BaseProto.BuffPt.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(buff_);
                buff_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.BuffProto.internal_static_BuffRsp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.BuffProto.internal_static_BuffRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.BuffProto.BuffRsp.class, proto.BuffProto.BuffRsp.Builder.class);
    }

    private int bitField0_;
    public static final int ISSUCC_FIELD_NUMBER = 1;
    private boolean isSucc_;
    /**
     * <pre>
     *是否成功;
     * </pre>
     *
     * <code>required bool isSucc = 1;</code>
     */
    public boolean hasIsSucc() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *是否成功;
     * </pre>
     *
     * <code>required bool isSucc = 1;</code>
     */
    public boolean getIsSucc() {
      return isSucc_;
    }

    public static final int ERRMESS_FIELD_NUMBER = 2;
    private volatile java.lang.Object errMess_;
    /**
     * <pre>
     *错误信息;
     * </pre>
     *
     * <code>optional string errMess = 2;</code>
     */
    public boolean hasErrMess() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     *错误信息;
     * </pre>
     *
     * <code>optional string errMess = 2;</code>
     */
    public java.lang.String getErrMess() {
      java.lang.Object ref = errMess_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errMess_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *错误信息;
     * </pre>
     *
     * <code>optional string errMess = 2;</code>
     */
    public com.google.protobuf.ByteString
        getErrMessBytes() {
      java.lang.Object ref = errMess_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errMess_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BUFF_FIELD_NUMBER = 3;
    private proto.BaseProto.BuffPt buff_;
    /**
     * <pre>
     *buff数据
     * </pre>
     *
     * <code>optional .BuffPt buff = 3;</code>
     */
    public boolean hasBuff() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     *buff数据
     * </pre>
     *
     * <code>optional .BuffPt buff = 3;</code>
     */
    public proto.BaseProto.BuffPt getBuff() {
      return buff_ == null ? proto.BaseProto.BuffPt.getDefaultInstance() : buff_;
    }
    /**
     * <pre>
     *buff数据
     * </pre>
     *
     * <code>optional .BuffPt buff = 3;</code>
     */
    public proto.BaseProto.BuffPtOrBuilder getBuffOrBuilder() {
      return buff_ == null ? proto.BaseProto.BuffPt.getDefaultInstance() : buff_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasIsSucc()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasBuff()) {
        if (!getBuff().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBool(1, isSucc_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errMess_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeMessage(3, getBuff());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isSucc_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, errMess_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getBuff());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.BuffProto.BuffRsp)) {
        return super.equals(obj);
      }
      proto.BuffProto.BuffRsp other = (proto.BuffProto.BuffRsp) obj;

      if (hasIsSucc() != other.hasIsSucc()) return false;
      if (hasIsSucc()) {
        if (getIsSucc()
            != other.getIsSucc()) return false;
      }
      if (hasErrMess() != other.hasErrMess()) return false;
      if (hasErrMess()) {
        if (!getErrMess()
            .equals(other.getErrMess())) return false;
      }
      if (hasBuff() != other.hasBuff()) return false;
      if (hasBuff()) {
        if (!getBuff()
            .equals(other.getBuff())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasIsSucc()) {
        hash = (37 * hash) + ISSUCC_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIsSucc());
      }
      if (hasErrMess()) {
        hash = (37 * hash) + ERRMESS_FIELD_NUMBER;
        hash = (53 * hash) + getErrMess().hashCode();
      }
      if (hasBuff()) {
        hash = (37 * hash) + BUFF_FIELD_NUMBER;
        hash = (53 * hash) + getBuff().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.BuffProto.BuffRsp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.BuffProto.BuffRsp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.BuffProto.BuffRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.BuffProto.BuffRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.BuffProto.BuffRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.BuffProto.BuffRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.BuffProto.BuffRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.BuffProto.BuffRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.BuffProto.BuffRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.BuffProto.BuffRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.BuffProto.BuffRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.BuffProto.BuffRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.BuffProto.BuffRsp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * buff返回
     *cmd:5011
     * </pre>
     *
     * Protobuf type {@code BuffRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BuffRsp)
        proto.BuffProto.BuffRspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.BuffProto.internal_static_BuffRsp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.BuffProto.internal_static_BuffRsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.BuffProto.BuffRsp.class, proto.BuffProto.BuffRsp.Builder.class);
      }

      // Construct using proto.BuffProto.BuffRsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBuffFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        isSucc_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        errMess_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (buffBuilder_ == null) {
          buff_ = null;
        } else {
          buffBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.BuffProto.internal_static_BuffRsp_descriptor;
      }

      @java.lang.Override
      public proto.BuffProto.BuffRsp getDefaultInstanceForType() {
        return proto.BuffProto.BuffRsp.getDefaultInstance();
      }

      @java.lang.Override
      public proto.BuffProto.BuffRsp build() {
        proto.BuffProto.BuffRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.BuffProto.BuffRsp buildPartial() {
        proto.BuffProto.BuffRsp result = new proto.BuffProto.BuffRsp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.isSucc_ = isSucc_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.errMess_ = errMess_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          if (buffBuilder_ == null) {
            result.buff_ = buff_;
          } else {
            result.buff_ = buffBuilder_.build();
          }
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.BuffProto.BuffRsp) {
          return mergeFrom((proto.BuffProto.BuffRsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.BuffProto.BuffRsp other) {
        if (other == proto.BuffProto.BuffRsp.getDefaultInstance()) return this;
        if (other.hasIsSucc()) {
          setIsSucc(other.getIsSucc());
        }
        if (other.hasErrMess()) {
          bitField0_ |= 0x00000002;
          errMess_ = other.errMess_;
          onChanged();
        }
        if (other.hasBuff()) {
          mergeBuff(other.getBuff());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasIsSucc()) {
          return false;
        }
        if (hasBuff()) {
          if (!getBuff().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.BuffProto.BuffRsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.BuffProto.BuffRsp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean isSucc_ ;
      /**
       * <pre>
       *是否成功;
       * </pre>
       *
       * <code>required bool isSucc = 1;</code>
       */
      public boolean hasIsSucc() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *是否成功;
       * </pre>
       *
       * <code>required bool isSucc = 1;</code>
       */
      public boolean getIsSucc() {
        return isSucc_;
      }
      /**
       * <pre>
       *是否成功;
       * </pre>
       *
       * <code>required bool isSucc = 1;</code>
       */
      public Builder setIsSucc(boolean value) {
        bitField0_ |= 0x00000001;
        isSucc_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否成功;
       * </pre>
       *
       * <code>required bool isSucc = 1;</code>
       */
      public Builder clearIsSucc() {
        bitField0_ = (bitField0_ & ~0x00000001);
        isSucc_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object errMess_ = "";
      /**
       * <pre>
       *错误信息;
       * </pre>
       *
       * <code>optional string errMess = 2;</code>
       */
      public boolean hasErrMess() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       *错误信息;
       * </pre>
       *
       * <code>optional string errMess = 2;</code>
       */
      public java.lang.String getErrMess() {
        java.lang.Object ref = errMess_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            errMess_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *错误信息;
       * </pre>
       *
       * <code>optional string errMess = 2;</code>
       */
      public com.google.protobuf.ByteString
          getErrMessBytes() {
        java.lang.Object ref = errMess_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errMess_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *错误信息;
       * </pre>
       *
       * <code>optional string errMess = 2;</code>
       */
      public Builder setErrMess(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errMess_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *错误信息;
       * </pre>
       *
       * <code>optional string errMess = 2;</code>
       */
      public Builder clearErrMess() {
        bitField0_ = (bitField0_ & ~0x00000002);
        errMess_ = getDefaultInstance().getErrMess();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *错误信息;
       * </pre>
       *
       * <code>optional string errMess = 2;</code>
       */
      public Builder setErrMessBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errMess_ = value;
        onChanged();
        return this;
      }

      private proto.BaseProto.BuffPt buff_;
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.BaseProto.BuffPt, proto.BaseProto.BuffPt.Builder, proto.BaseProto.BuffPtOrBuilder> buffBuilder_;
      /**
       * <pre>
       *buff数据
       * </pre>
       *
       * <code>optional .BuffPt buff = 3;</code>
       */
      public boolean hasBuff() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       *buff数据
       * </pre>
       *
       * <code>optional .BuffPt buff = 3;</code>
       */
      public proto.BaseProto.BuffPt getBuff() {
        if (buffBuilder_ == null) {
          return buff_ == null ? proto.BaseProto.BuffPt.getDefaultInstance() : buff_;
        } else {
          return buffBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *buff数据
       * </pre>
       *
       * <code>optional .BuffPt buff = 3;</code>
       */
      public Builder setBuff(proto.BaseProto.BuffPt value) {
        if (buffBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          buff_ = value;
          onChanged();
        } else {
          buffBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <pre>
       *buff数据
       * </pre>
       *
       * <code>optional .BuffPt buff = 3;</code>
       */
      public Builder setBuff(
          proto.BaseProto.BuffPt.Builder builderForValue) {
        if (buffBuilder_ == null) {
          buff_ = builderForValue.build();
          onChanged();
        } else {
          buffBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <pre>
       *buff数据
       * </pre>
       *
       * <code>optional .BuffPt buff = 3;</code>
       */
      public Builder mergeBuff(proto.BaseProto.BuffPt value) {
        if (buffBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
              buff_ != null &&
              buff_ != proto.BaseProto.BuffPt.getDefaultInstance()) {
            buff_ =
              proto.BaseProto.BuffPt.newBuilder(buff_).mergeFrom(value).buildPartial();
          } else {
            buff_ = value;
          }
          onChanged();
        } else {
          buffBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <pre>
       *buff数据
       * </pre>
       *
       * <code>optional .BuffPt buff = 3;</code>
       */
      public Builder clearBuff() {
        if (buffBuilder_ == null) {
          buff_ = null;
          onChanged();
        } else {
          buffBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <pre>
       *buff数据
       * </pre>
       *
       * <code>optional .BuffPt buff = 3;</code>
       */
      public proto.BaseProto.BuffPt.Builder getBuffBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getBuffFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *buff数据
       * </pre>
       *
       * <code>optional .BuffPt buff = 3;</code>
       */
      public proto.BaseProto.BuffPtOrBuilder getBuffOrBuilder() {
        if (buffBuilder_ != null) {
          return buffBuilder_.getMessageOrBuilder();
        } else {
          return buff_ == null ?
              proto.BaseProto.BuffPt.getDefaultInstance() : buff_;
        }
      }
      /**
       * <pre>
       *buff数据
       * </pre>
       *
       * <code>optional .BuffPt buff = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.BaseProto.BuffPt, proto.BaseProto.BuffPt.Builder, proto.BaseProto.BuffPtOrBuilder> 
          getBuffFieldBuilder() {
        if (buffBuilder_ == null) {
          buffBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto.BaseProto.BuffPt, proto.BaseProto.BuffPt.Builder, proto.BaseProto.BuffPtOrBuilder>(
                  getBuff(),
                  getParentForChildren(),
                  isClean());
          buff_ = null;
        }
        return buffBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BuffRsp)
    }

    // @@protoc_insertion_point(class_scope:BuffRsp)
    private static final proto.BuffProto.BuffRsp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.BuffProto.BuffRsp();
    }

    public static proto.BuffProto.BuffRsp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<BuffRsp>
        PARSER = new com.google.protobuf.AbstractParser<BuffRsp>() {
      @java.lang.Override
      public BuffRsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BuffRsp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BuffRsp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BuffRsp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.BuffProto.BuffRsp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BuffReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BuffReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BuffRsp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BuffRsp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nbuff.proto\032\nbase.proto\"\031\n\007BuffReq\022\016\n\006b" +
      "uffId\030\001 \002(\005\"A\n\007BuffRsp\022\016\n\006isSucc\030\001 \002(\010\022\017" +
      "\n\007errMess\030\002 \001(\t\022\025\n\004buff\030\003 \001(\0132\007.BuffPtB\024" +
      "\n\005protoB\tBuffProtoP\000"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          proto.BaseProto.getDescriptor(),
        }, assigner);
    internal_static_BuffReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BuffReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BuffReq_descriptor,
        new java.lang.String[] { "BuffId", });
    internal_static_BuffRsp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BuffRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BuffRsp_descriptor,
        new java.lang.String[] { "IsSucc", "ErrMess", "Buff", });
    proto.BaseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
