// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rank.proto

package proto;

public final class RankProto {
  private RankProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RankReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RankReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *排行榜类型（1：周榜，2：日榜）
     * </pre>
     *
     * <code>required int32 type = 1;</code>
     */
    boolean hasType();
    /**
     * <pre>
     *排行榜类型（1：周榜，2：日榜）
     * </pre>
     *
     * <code>required int32 type = 1;</code>
     */
    int getType();
  }
  /**
   * <pre>
   * 排行榜请求
   *cmd:1008
   * </pre>
   *
   * Protobuf type {@code RankReq}
   */
  public  static final class RankReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RankReq)
      RankReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RankReq.newBuilder() to construct.
    private RankReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RankReq() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RankReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              type_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.RankProto.internal_static_RankReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.RankProto.internal_static_RankReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.RankProto.RankReq.class, proto.RankProto.RankReq.Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <pre>
     *排行榜类型（1：周榜，2：日榜）
     * </pre>
     *
     * <code>required int32 type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *排行榜类型（1：周榜，2：日榜）
     * </pre>
     *
     * <code>required int32 type = 1;</code>
     */
    public int getType() {
      return type_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, type_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.RankProto.RankReq)) {
        return super.equals(obj);
      }
      proto.RankProto.RankReq other = (proto.RankProto.RankReq) obj;

      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (getType()
            != other.getType()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.RankProto.RankReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RankProto.RankReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RankProto.RankReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RankProto.RankReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RankProto.RankReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RankProto.RankReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RankProto.RankReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.RankProto.RankReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.RankProto.RankReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.RankProto.RankReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.RankProto.RankReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.RankProto.RankReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.RankProto.RankReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 排行榜请求
     *cmd:1008
     * </pre>
     *
     * Protobuf type {@code RankReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RankReq)
        proto.RankProto.RankReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.RankProto.internal_static_RankReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.RankProto.internal_static_RankReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.RankProto.RankReq.class, proto.RankProto.RankReq.Builder.class);
      }

      // Construct using proto.RankProto.RankReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.RankProto.internal_static_RankReq_descriptor;
      }

      @java.lang.Override
      public proto.RankProto.RankReq getDefaultInstanceForType() {
        return proto.RankProto.RankReq.getDefaultInstance();
      }

      @java.lang.Override
      public proto.RankProto.RankReq build() {
        proto.RankProto.RankReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.RankProto.RankReq buildPartial() {
        proto.RankProto.RankReq result = new proto.RankProto.RankReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.type_ = type_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.RankProto.RankReq) {
          return mergeFrom((proto.RankProto.RankReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.RankProto.RankReq other) {
        if (other == proto.RankProto.RankReq.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasType()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.RankProto.RankReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.RankProto.RankReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ ;
      /**
       * <pre>
       *排行榜类型（1：周榜，2：日榜）
       * </pre>
       *
       * <code>required int32 type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *排行榜类型（1：周榜，2：日榜）
       * </pre>
       *
       * <code>required int32 type = 1;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <pre>
       *排行榜类型（1：周榜，2：日榜）
       * </pre>
       *
       * <code>required int32 type = 1;</code>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *排行榜类型（1：周榜，2：日榜）
       * </pre>
       *
       * <code>required int32 type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RankReq)
    }

    // @@protoc_insertion_point(class_scope:RankReq)
    private static final proto.RankProto.RankReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.RankProto.RankReq();
    }

    public static proto.RankProto.RankReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<RankReq>
        PARSER = new com.google.protobuf.AbstractParser<RankReq>() {
      @java.lang.Override
      public RankReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RankReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RankReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RankReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.RankProto.RankReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RankRspOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RankRsp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *是否成功;
     * </pre>
     *
     * <code>required bool isSucc = 1;</code>
     */
    boolean hasIsSucc();
    /**
     * <pre>
     *是否成功;
     * </pre>
     *
     * <code>required bool isSucc = 1;</code>
     */
    boolean getIsSucc();

    /**
     * <pre>
     *错误信息;
     * </pre>
     *
     * <code>optional string errMess = 2;</code>
     */
    boolean hasErrMess();
    /**
     * <pre>
     *错误信息;
     * </pre>
     *
     * <code>optional string errMess = 2;</code>
     */
    java.lang.String getErrMess();
    /**
     * <pre>
     *错误信息;
     * </pre>
     *
     * <code>optional string errMess = 2;</code>
     */
    com.google.protobuf.ByteString
        getErrMessBytes();

    /**
     * <pre>
     *排行榜类型（1：周榜，2：日榜）
     * </pre>
     *
     * <code>required int32 type = 3;</code>
     */
    boolean hasType();
    /**
     * <pre>
     *排行榜类型（1：周榜，2：日榜）
     * </pre>
     *
     * <code>required int32 type = 3;</code>
     */
    int getType();

    /**
     * <pre>
     *自己的排行信息，没入榜则不传
     * </pre>
     *
     * <code>optional .RankInfoPt myRank = 4;</code>
     */
    boolean hasMyRank();
    /**
     * <pre>
     *自己的排行信息，没入榜则不传
     * </pre>
     *
     * <code>optional .RankInfoPt myRank = 4;</code>
     */
    proto.BaseProto.RankInfoPt getMyRank();
    /**
     * <pre>
     *自己的排行信息，没入榜则不传
     * </pre>
     *
     * <code>optional .RankInfoPt myRank = 4;</code>
     */
    proto.BaseProto.RankInfoPtOrBuilder getMyRankOrBuilder();

    /**
     * <code>repeated .RankInfoPt rankPt = 5;</code>
     */
    java.util.List<proto.BaseProto.RankInfoPt> 
        getRankPtList();
    /**
     * <code>repeated .RankInfoPt rankPt = 5;</code>
     */
    proto.BaseProto.RankInfoPt getRankPt(int index);
    /**
     * <code>repeated .RankInfoPt rankPt = 5;</code>
     */
    int getRankPtCount();
    /**
     * <code>repeated .RankInfoPt rankPt = 5;</code>
     */
    java.util.List<? extends proto.BaseProto.RankInfoPtOrBuilder> 
        getRankPtOrBuilderList();
    /**
     * <code>repeated .RankInfoPt rankPt = 5;</code>
     */
    proto.BaseProto.RankInfoPtOrBuilder getRankPtOrBuilder(
        int index);
  }
  /**
   * <pre>
   * 排行榜返回
   *cmd:5008
   * </pre>
   *
   * Protobuf type {@code RankRsp}
   */
  public  static final class RankRsp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RankRsp)
      RankRspOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RankRsp.newBuilder() to construct.
    private RankRsp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RankRsp() {
      errMess_ = "";
      rankPt_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RankRsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              isSucc_ = input.readBool();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              errMess_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              type_ = input.readInt32();
              break;
            }
            case 34: {
              proto.BaseProto.RankInfoPt.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) != 0)) {
                subBuilder = myRank_.toBuilder();
              }
              myRank_ = input.readMessage(proto.BaseProto.RankInfoPt.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(myRank_);
                myRank_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) != 0)) {
                rankPt_ = new java.util.ArrayList<proto.BaseProto.RankInfoPt>();
                mutable_bitField0_ |= 0x00000010;
              }
              rankPt_.add(
                  input.readMessage(proto.BaseProto.RankInfoPt.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) != 0)) {
          rankPt_ = java.util.Collections.unmodifiableList(rankPt_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.RankProto.internal_static_RankRsp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.RankProto.internal_static_RankRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.RankProto.RankRsp.class, proto.RankProto.RankRsp.Builder.class);
    }

    private int bitField0_;
    public static final int ISSUCC_FIELD_NUMBER = 1;
    private boolean isSucc_;
    /**
     * <pre>
     *是否成功;
     * </pre>
     *
     * <code>required bool isSucc = 1;</code>
     */
    public boolean hasIsSucc() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *是否成功;
     * </pre>
     *
     * <code>required bool isSucc = 1;</code>
     */
    public boolean getIsSucc() {
      return isSucc_;
    }

    public static final int ERRMESS_FIELD_NUMBER = 2;
    private volatile java.lang.Object errMess_;
    /**
     * <pre>
     *错误信息;
     * </pre>
     *
     * <code>optional string errMess = 2;</code>
     */
    public boolean hasErrMess() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     *错误信息;
     * </pre>
     *
     * <code>optional string errMess = 2;</code>
     */
    public java.lang.String getErrMess() {
      java.lang.Object ref = errMess_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errMess_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *错误信息;
     * </pre>
     *
     * <code>optional string errMess = 2;</code>
     */
    public com.google.protobuf.ByteString
        getErrMessBytes() {
      java.lang.Object ref = errMess_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errMess_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <pre>
     *排行榜类型（1：周榜，2：日榜）
     * </pre>
     *
     * <code>required int32 type = 3;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     *排行榜类型（1：周榜，2：日榜）
     * </pre>
     *
     * <code>required int32 type = 3;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int MYRANK_FIELD_NUMBER = 4;
    private proto.BaseProto.RankInfoPt myRank_;
    /**
     * <pre>
     *自己的排行信息，没入榜则不传
     * </pre>
     *
     * <code>optional .RankInfoPt myRank = 4;</code>
     */
    public boolean hasMyRank() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     *自己的排行信息，没入榜则不传
     * </pre>
     *
     * <code>optional .RankInfoPt myRank = 4;</code>
     */
    public proto.BaseProto.RankInfoPt getMyRank() {
      return myRank_ == null ? proto.BaseProto.RankInfoPt.getDefaultInstance() : myRank_;
    }
    /**
     * <pre>
     *自己的排行信息，没入榜则不传
     * </pre>
     *
     * <code>optional .RankInfoPt myRank = 4;</code>
     */
    public proto.BaseProto.RankInfoPtOrBuilder getMyRankOrBuilder() {
      return myRank_ == null ? proto.BaseProto.RankInfoPt.getDefaultInstance() : myRank_;
    }

    public static final int RANKPT_FIELD_NUMBER = 5;
    private java.util.List<proto.BaseProto.RankInfoPt> rankPt_;
    /**
     * <code>repeated .RankInfoPt rankPt = 5;</code>
     */
    public java.util.List<proto.BaseProto.RankInfoPt> getRankPtList() {
      return rankPt_;
    }
    /**
     * <code>repeated .RankInfoPt rankPt = 5;</code>
     */
    public java.util.List<? extends proto.BaseProto.RankInfoPtOrBuilder> 
        getRankPtOrBuilderList() {
      return rankPt_;
    }
    /**
     * <code>repeated .RankInfoPt rankPt = 5;</code>
     */
    public int getRankPtCount() {
      return rankPt_.size();
    }
    /**
     * <code>repeated .RankInfoPt rankPt = 5;</code>
     */
    public proto.BaseProto.RankInfoPt getRankPt(int index) {
      return rankPt_.get(index);
    }
    /**
     * <code>repeated .RankInfoPt rankPt = 5;</code>
     */
    public proto.BaseProto.RankInfoPtOrBuilder getRankPtOrBuilder(
        int index) {
      return rankPt_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasIsSucc()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasMyRank()) {
        if (!getMyRank().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getRankPtCount(); i++) {
        if (!getRankPt(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBool(1, isSucc_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errMess_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, type_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeMessage(4, getMyRank());
      }
      for (int i = 0; i < rankPt_.size(); i++) {
        output.writeMessage(5, rankPt_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isSucc_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, errMess_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, type_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getMyRank());
      }
      for (int i = 0; i < rankPt_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, rankPt_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.RankProto.RankRsp)) {
        return super.equals(obj);
      }
      proto.RankProto.RankRsp other = (proto.RankProto.RankRsp) obj;

      if (hasIsSucc() != other.hasIsSucc()) return false;
      if (hasIsSucc()) {
        if (getIsSucc()
            != other.getIsSucc()) return false;
      }
      if (hasErrMess() != other.hasErrMess()) return false;
      if (hasErrMess()) {
        if (!getErrMess()
            .equals(other.getErrMess())) return false;
      }
      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (getType()
            != other.getType()) return false;
      }
      if (hasMyRank() != other.hasMyRank()) return false;
      if (hasMyRank()) {
        if (!getMyRank()
            .equals(other.getMyRank())) return false;
      }
      if (!getRankPtList()
          .equals(other.getRankPtList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasIsSucc()) {
        hash = (37 * hash) + ISSUCC_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIsSucc());
      }
      if (hasErrMess()) {
        hash = (37 * hash) + ERRMESS_FIELD_NUMBER;
        hash = (53 * hash) + getErrMess().hashCode();
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType();
      }
      if (hasMyRank()) {
        hash = (37 * hash) + MYRANK_FIELD_NUMBER;
        hash = (53 * hash) + getMyRank().hashCode();
      }
      if (getRankPtCount() > 0) {
        hash = (37 * hash) + RANKPT_FIELD_NUMBER;
        hash = (53 * hash) + getRankPtList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.RankProto.RankRsp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RankProto.RankRsp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RankProto.RankRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RankProto.RankRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RankProto.RankRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RankProto.RankRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RankProto.RankRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.RankProto.RankRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.RankProto.RankRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.RankProto.RankRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.RankProto.RankRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.RankProto.RankRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.RankProto.RankRsp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 排行榜返回
     *cmd:5008
     * </pre>
     *
     * Protobuf type {@code RankRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RankRsp)
        proto.RankProto.RankRspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.RankProto.internal_static_RankRsp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.RankProto.internal_static_RankRsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.RankProto.RankRsp.class, proto.RankProto.RankRsp.Builder.class);
      }

      // Construct using proto.RankProto.RankRsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMyRankFieldBuilder();
          getRankPtFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        isSucc_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        errMess_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (myRankBuilder_ == null) {
          myRank_ = null;
        } else {
          myRankBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        if (rankPtBuilder_ == null) {
          rankPt_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          rankPtBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.RankProto.internal_static_RankRsp_descriptor;
      }

      @java.lang.Override
      public proto.RankProto.RankRsp getDefaultInstanceForType() {
        return proto.RankProto.RankRsp.getDefaultInstance();
      }

      @java.lang.Override
      public proto.RankProto.RankRsp build() {
        proto.RankProto.RankRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.RankProto.RankRsp buildPartial() {
        proto.RankProto.RankRsp result = new proto.RankProto.RankRsp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.isSucc_ = isSucc_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.errMess_ = errMess_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.type_ = type_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          if (myRankBuilder_ == null) {
            result.myRank_ = myRank_;
          } else {
            result.myRank_ = myRankBuilder_.build();
          }
          to_bitField0_ |= 0x00000008;
        }
        if (rankPtBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0)) {
            rankPt_ = java.util.Collections.unmodifiableList(rankPt_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.rankPt_ = rankPt_;
        } else {
          result.rankPt_ = rankPtBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.RankProto.RankRsp) {
          return mergeFrom((proto.RankProto.RankRsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.RankProto.RankRsp other) {
        if (other == proto.RankProto.RankRsp.getDefaultInstance()) return this;
        if (other.hasIsSucc()) {
          setIsSucc(other.getIsSucc());
        }
        if (other.hasErrMess()) {
          bitField0_ |= 0x00000002;
          errMess_ = other.errMess_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasMyRank()) {
          mergeMyRank(other.getMyRank());
        }
        if (rankPtBuilder_ == null) {
          if (!other.rankPt_.isEmpty()) {
            if (rankPt_.isEmpty()) {
              rankPt_ = other.rankPt_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureRankPtIsMutable();
              rankPt_.addAll(other.rankPt_);
            }
            onChanged();
          }
        } else {
          if (!other.rankPt_.isEmpty()) {
            if (rankPtBuilder_.isEmpty()) {
              rankPtBuilder_.dispose();
              rankPtBuilder_ = null;
              rankPt_ = other.rankPt_;
              bitField0_ = (bitField0_ & ~0x00000010);
              rankPtBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRankPtFieldBuilder() : null;
            } else {
              rankPtBuilder_.addAllMessages(other.rankPt_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasIsSucc()) {
          return false;
        }
        if (!hasType()) {
          return false;
        }
        if (hasMyRank()) {
          if (!getMyRank().isInitialized()) {
            return false;
          }
        }
        for (int i = 0; i < getRankPtCount(); i++) {
          if (!getRankPt(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.RankProto.RankRsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.RankProto.RankRsp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean isSucc_ ;
      /**
       * <pre>
       *是否成功;
       * </pre>
       *
       * <code>required bool isSucc = 1;</code>
       */
      public boolean hasIsSucc() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *是否成功;
       * </pre>
       *
       * <code>required bool isSucc = 1;</code>
       */
      public boolean getIsSucc() {
        return isSucc_;
      }
      /**
       * <pre>
       *是否成功;
       * </pre>
       *
       * <code>required bool isSucc = 1;</code>
       */
      public Builder setIsSucc(boolean value) {
        bitField0_ |= 0x00000001;
        isSucc_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否成功;
       * </pre>
       *
       * <code>required bool isSucc = 1;</code>
       */
      public Builder clearIsSucc() {
        bitField0_ = (bitField0_ & ~0x00000001);
        isSucc_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object errMess_ = "";
      /**
       * <pre>
       *错误信息;
       * </pre>
       *
       * <code>optional string errMess = 2;</code>
       */
      public boolean hasErrMess() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       *错误信息;
       * </pre>
       *
       * <code>optional string errMess = 2;</code>
       */
      public java.lang.String getErrMess() {
        java.lang.Object ref = errMess_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            errMess_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *错误信息;
       * </pre>
       *
       * <code>optional string errMess = 2;</code>
       */
      public com.google.protobuf.ByteString
          getErrMessBytes() {
        java.lang.Object ref = errMess_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errMess_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *错误信息;
       * </pre>
       *
       * <code>optional string errMess = 2;</code>
       */
      public Builder setErrMess(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errMess_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *错误信息;
       * </pre>
       *
       * <code>optional string errMess = 2;</code>
       */
      public Builder clearErrMess() {
        bitField0_ = (bitField0_ & ~0x00000002);
        errMess_ = getDefaultInstance().getErrMess();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *错误信息;
       * </pre>
       *
       * <code>optional string errMess = 2;</code>
       */
      public Builder setErrMessBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errMess_ = value;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <pre>
       *排行榜类型（1：周榜，2：日榜）
       * </pre>
       *
       * <code>required int32 type = 3;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       *排行榜类型（1：周榜，2：日榜）
       * </pre>
       *
       * <code>required int32 type = 3;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <pre>
       *排行榜类型（1：周榜，2：日榜）
       * </pre>
       *
       * <code>required int32 type = 3;</code>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *排行榜类型（1：周榜，2：日榜）
       * </pre>
       *
       * <code>required int32 type = 3;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = 0;
        onChanged();
        return this;
      }

      private proto.BaseProto.RankInfoPt myRank_;
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.BaseProto.RankInfoPt, proto.BaseProto.RankInfoPt.Builder, proto.BaseProto.RankInfoPtOrBuilder> myRankBuilder_;
      /**
       * <pre>
       *自己的排行信息，没入榜则不传
       * </pre>
       *
       * <code>optional .RankInfoPt myRank = 4;</code>
       */
      public boolean hasMyRank() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       *自己的排行信息，没入榜则不传
       * </pre>
       *
       * <code>optional .RankInfoPt myRank = 4;</code>
       */
      public proto.BaseProto.RankInfoPt getMyRank() {
        if (myRankBuilder_ == null) {
          return myRank_ == null ? proto.BaseProto.RankInfoPt.getDefaultInstance() : myRank_;
        } else {
          return myRankBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *自己的排行信息，没入榜则不传
       * </pre>
       *
       * <code>optional .RankInfoPt myRank = 4;</code>
       */
      public Builder setMyRank(proto.BaseProto.RankInfoPt value) {
        if (myRankBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          myRank_ = value;
          onChanged();
        } else {
          myRankBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <pre>
       *自己的排行信息，没入榜则不传
       * </pre>
       *
       * <code>optional .RankInfoPt myRank = 4;</code>
       */
      public Builder setMyRank(
          proto.BaseProto.RankInfoPt.Builder builderForValue) {
        if (myRankBuilder_ == null) {
          myRank_ = builderForValue.build();
          onChanged();
        } else {
          myRankBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <pre>
       *自己的排行信息，没入榜则不传
       * </pre>
       *
       * <code>optional .RankInfoPt myRank = 4;</code>
       */
      public Builder mergeMyRank(proto.BaseProto.RankInfoPt value) {
        if (myRankBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
              myRank_ != null &&
              myRank_ != proto.BaseProto.RankInfoPt.getDefaultInstance()) {
            myRank_ =
              proto.BaseProto.RankInfoPt.newBuilder(myRank_).mergeFrom(value).buildPartial();
          } else {
            myRank_ = value;
          }
          onChanged();
        } else {
          myRankBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <pre>
       *自己的排行信息，没入榜则不传
       * </pre>
       *
       * <code>optional .RankInfoPt myRank = 4;</code>
       */
      public Builder clearMyRank() {
        if (myRankBuilder_ == null) {
          myRank_ = null;
          onChanged();
        } else {
          myRankBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <pre>
       *自己的排行信息，没入榜则不传
       * </pre>
       *
       * <code>optional .RankInfoPt myRank = 4;</code>
       */
      public proto.BaseProto.RankInfoPt.Builder getMyRankBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getMyRankFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *自己的排行信息，没入榜则不传
       * </pre>
       *
       * <code>optional .RankInfoPt myRank = 4;</code>
       */
      public proto.BaseProto.RankInfoPtOrBuilder getMyRankOrBuilder() {
        if (myRankBuilder_ != null) {
          return myRankBuilder_.getMessageOrBuilder();
        } else {
          return myRank_ == null ?
              proto.BaseProto.RankInfoPt.getDefaultInstance() : myRank_;
        }
      }
      /**
       * <pre>
       *自己的排行信息，没入榜则不传
       * </pre>
       *
       * <code>optional .RankInfoPt myRank = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.BaseProto.RankInfoPt, proto.BaseProto.RankInfoPt.Builder, proto.BaseProto.RankInfoPtOrBuilder> 
          getMyRankFieldBuilder() {
        if (myRankBuilder_ == null) {
          myRankBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto.BaseProto.RankInfoPt, proto.BaseProto.RankInfoPt.Builder, proto.BaseProto.RankInfoPtOrBuilder>(
                  getMyRank(),
                  getParentForChildren(),
                  isClean());
          myRank_ = null;
        }
        return myRankBuilder_;
      }

      private java.util.List<proto.BaseProto.RankInfoPt> rankPt_ =
        java.util.Collections.emptyList();
      private void ensureRankPtIsMutable() {
        if (!((bitField0_ & 0x00000010) != 0)) {
          rankPt_ = new java.util.ArrayList<proto.BaseProto.RankInfoPt>(rankPt_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.BaseProto.RankInfoPt, proto.BaseProto.RankInfoPt.Builder, proto.BaseProto.RankInfoPtOrBuilder> rankPtBuilder_;

      /**
       * <code>repeated .RankInfoPt rankPt = 5;</code>
       */
      public java.util.List<proto.BaseProto.RankInfoPt> getRankPtList() {
        if (rankPtBuilder_ == null) {
          return java.util.Collections.unmodifiableList(rankPt_);
        } else {
          return rankPtBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .RankInfoPt rankPt = 5;</code>
       */
      public int getRankPtCount() {
        if (rankPtBuilder_ == null) {
          return rankPt_.size();
        } else {
          return rankPtBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .RankInfoPt rankPt = 5;</code>
       */
      public proto.BaseProto.RankInfoPt getRankPt(int index) {
        if (rankPtBuilder_ == null) {
          return rankPt_.get(index);
        } else {
          return rankPtBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .RankInfoPt rankPt = 5;</code>
       */
      public Builder setRankPt(
          int index, proto.BaseProto.RankInfoPt value) {
        if (rankPtBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRankPtIsMutable();
          rankPt_.set(index, value);
          onChanged();
        } else {
          rankPtBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .RankInfoPt rankPt = 5;</code>
       */
      public Builder setRankPt(
          int index, proto.BaseProto.RankInfoPt.Builder builderForValue) {
        if (rankPtBuilder_ == null) {
          ensureRankPtIsMutable();
          rankPt_.set(index, builderForValue.build());
          onChanged();
        } else {
          rankPtBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .RankInfoPt rankPt = 5;</code>
       */
      public Builder addRankPt(proto.BaseProto.RankInfoPt value) {
        if (rankPtBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRankPtIsMutable();
          rankPt_.add(value);
          onChanged();
        } else {
          rankPtBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .RankInfoPt rankPt = 5;</code>
       */
      public Builder addRankPt(
          int index, proto.BaseProto.RankInfoPt value) {
        if (rankPtBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRankPtIsMutable();
          rankPt_.add(index, value);
          onChanged();
        } else {
          rankPtBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .RankInfoPt rankPt = 5;</code>
       */
      public Builder addRankPt(
          proto.BaseProto.RankInfoPt.Builder builderForValue) {
        if (rankPtBuilder_ == null) {
          ensureRankPtIsMutable();
          rankPt_.add(builderForValue.build());
          onChanged();
        } else {
          rankPtBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .RankInfoPt rankPt = 5;</code>
       */
      public Builder addRankPt(
          int index, proto.BaseProto.RankInfoPt.Builder builderForValue) {
        if (rankPtBuilder_ == null) {
          ensureRankPtIsMutable();
          rankPt_.add(index, builderForValue.build());
          onChanged();
        } else {
          rankPtBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .RankInfoPt rankPt = 5;</code>
       */
      public Builder addAllRankPt(
          java.lang.Iterable<? extends proto.BaseProto.RankInfoPt> values) {
        if (rankPtBuilder_ == null) {
          ensureRankPtIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, rankPt_);
          onChanged();
        } else {
          rankPtBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .RankInfoPt rankPt = 5;</code>
       */
      public Builder clearRankPt() {
        if (rankPtBuilder_ == null) {
          rankPt_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          rankPtBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .RankInfoPt rankPt = 5;</code>
       */
      public Builder removeRankPt(int index) {
        if (rankPtBuilder_ == null) {
          ensureRankPtIsMutable();
          rankPt_.remove(index);
          onChanged();
        } else {
          rankPtBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .RankInfoPt rankPt = 5;</code>
       */
      public proto.BaseProto.RankInfoPt.Builder getRankPtBuilder(
          int index) {
        return getRankPtFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .RankInfoPt rankPt = 5;</code>
       */
      public proto.BaseProto.RankInfoPtOrBuilder getRankPtOrBuilder(
          int index) {
        if (rankPtBuilder_ == null) {
          return rankPt_.get(index);  } else {
          return rankPtBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .RankInfoPt rankPt = 5;</code>
       */
      public java.util.List<? extends proto.BaseProto.RankInfoPtOrBuilder> 
           getRankPtOrBuilderList() {
        if (rankPtBuilder_ != null) {
          return rankPtBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(rankPt_);
        }
      }
      /**
       * <code>repeated .RankInfoPt rankPt = 5;</code>
       */
      public proto.BaseProto.RankInfoPt.Builder addRankPtBuilder() {
        return getRankPtFieldBuilder().addBuilder(
            proto.BaseProto.RankInfoPt.getDefaultInstance());
      }
      /**
       * <code>repeated .RankInfoPt rankPt = 5;</code>
       */
      public proto.BaseProto.RankInfoPt.Builder addRankPtBuilder(
          int index) {
        return getRankPtFieldBuilder().addBuilder(
            index, proto.BaseProto.RankInfoPt.getDefaultInstance());
      }
      /**
       * <code>repeated .RankInfoPt rankPt = 5;</code>
       */
      public java.util.List<proto.BaseProto.RankInfoPt.Builder> 
           getRankPtBuilderList() {
        return getRankPtFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.BaseProto.RankInfoPt, proto.BaseProto.RankInfoPt.Builder, proto.BaseProto.RankInfoPtOrBuilder> 
          getRankPtFieldBuilder() {
        if (rankPtBuilder_ == null) {
          rankPtBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              proto.BaseProto.RankInfoPt, proto.BaseProto.RankInfoPt.Builder, proto.BaseProto.RankInfoPtOrBuilder>(
                  rankPt_,
                  ((bitField0_ & 0x00000010) != 0),
                  getParentForChildren(),
                  isClean());
          rankPt_ = null;
        }
        return rankPtBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RankRsp)
    }

    // @@protoc_insertion_point(class_scope:RankRsp)
    private static final proto.RankProto.RankRsp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.RankProto.RankRsp();
    }

    public static proto.RankProto.RankRsp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<RankRsp>
        PARSER = new com.google.protobuf.AbstractParser<RankRsp>() {
      @java.lang.Override
      public RankRsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RankRsp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RankRsp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RankRsp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.RankProto.RankRsp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RankReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RankReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RankRsp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RankRsp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nrank.proto\032\nbase.proto\"\027\n\007RankReq\022\014\n\004t" +
      "ype\030\001 \002(\005\"r\n\007RankRsp\022\016\n\006isSucc\030\001 \002(\010\022\017\n\007" +
      "errMess\030\002 \001(\t\022\014\n\004type\030\003 \002(\005\022\033\n\006myRank\030\004 " +
      "\001(\0132\013.RankInfoPt\022\033\n\006rankPt\030\005 \003(\0132\013.RankI" +
      "nfoPtB\024\n\005protoB\tRankProtoP\000"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          proto.BaseProto.getDescriptor(),
        }, assigner);
    internal_static_RankReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RankReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RankReq_descriptor,
        new java.lang.String[] { "Type", });
    internal_static_RankRsp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RankRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RankRsp_descriptor,
        new java.lang.String[] { "IsSucc", "ErrMess", "Type", "MyRank", "RankPt", });
    proto.BaseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
